SAP/cloud-sdk-cli

.github/workflows/local-tests.yml
.github/workflows/publish-npm.yml
.github/workflows/release.yml
package-lock.json
package.json

Add a github action that publishes any commit from master to npmjs.com
In general avoid breaking changes, but if you think it is necessary give your reasoning in the _Further Comments_ section.

Add publish action

---

.github/workflows/test-branches.yml
.github/workflows/test-master.yml
README.md

This adds more information for new users how to use the CLI. Also a short paragraph on how to release a new version was added. Lastly I added badges for tests and downloads. Due to the behavior of the github actions badge, I split the tests to 2 different actions.

Improve Usage and Contribution section in README

---

README.md

Update description in readme.
In general avoid breaking changes, but if you think it is necessary give your reasoning in the _Further Comments_ section.

Add update instructions

---

src/templates/init/pipeline_config.yml.mu

The pipeline-config.yml contains some commented out section that are not necessary for people that are just starting out. Therefore I reduced it to the bare minimum + commented out config for a CF deploy

Simplify pipeline-config.yml

---

src/commands/init.ts
src/utils/jest-config.ts
src/utils/package-json.ts
src/utils/scaffold.ts
src/utils/templates.ts
test/init.spec.ts

In the scaffolding case, this enhances the package.json with some additional jest configuration which puts the required reports for unit tests in the according folders.

Add jest configuration for coverage and junit report

---

src/commands/add-approuter.ts
src/commands/add-cx-server.ts
src/commands/init.ts
src/utils/index.ts
src/utils/usage-analytics.ts
test/init.spec.ts
usage-analytics.md

Generate the necessary file (if given consent) to send analytics.
In general avoid breaking changes, but if you think it is necessary give your reasoning in the _Further Comments_ section.

Enable analytics

---

src/commands/init.ts
src/utils/usage-analytics.ts
test/init.spec.ts

Analytics are triggered during `npm install`. Therefore the file needs to be created earlier.

Ask if analytics should be enabled first

---

test/generate-vdm.spec.ts

Refactor generate vdm test

---

package.json
src/commands/add-approuter.ts
src/commands/add-cds.ts
src/commands/init.ts
src/utils/git-ignore.ts
src/utils/index.ts
src/utils/jest-config.ts
src/utils/package-json.ts
src/utils/scaffold.ts
src/utils/warnings.ts
test/init.spec.ts
test/utils/git-ignore.spec.ts
test/utils/warnings.spec.ts

Since we are using `listr`, we can't use `cli-ux` to output warnings as the list is displayed. Therefore the warnings are now collected and displayed in the "success" message at the end.

Warnings in success msg

---

package.json
src/utils/message-formatter.ts
yarn.lock

It took less code than the boxen config therefore I thought it might be worth it

Replace boxen with simpler implementation

---

src/utils/package-json.ts
src/utils/scaffold.ts

During #43 I created a fake warning and removed one fix for an avoidable warning for testing purposes and forgot to remove it. This PR fixes these mistakes.

Hotfix wrong or unnecessary warnings

---

src/commands/init.ts
src/templates/scaffold-readme/README.md
src/utils/scaffold.ts
test/init.spec.ts
test/utils/__snapshots__/scaffold.spec.ts.snap

The default Nest README.md was a bit confusing and is now replaced with our own README.md which should help new users get started quickly. This only affects scaffolded projects.

Create custom README for scaffolded projects

---

src/commands/add-approuter.ts
src/commands/add-cds.ts
src/commands/add-cx-server.ts
src/commands/help-page.ts
src/commands/init.ts
src/utils/package-json.ts
src/utils/templates.ts
test/__snapshots__/add-approuter.spec.ts.snap
test/__snapshots__/add-cds.spec.ts.snap
test/__snapshots__/add-cx-server.spec.ts.snap
test/__snapshots__/init.spec.ts.snap
test/add-approuter.spec.ts
test/add-cds.spec.ts
test/add-cx-server.spec.ts
test/generate-odata-client.spec.ts
test/init.spec.ts
test/utils/package-json.spec.ts

In an effort to remove the rather large 'cli-ux' package, I refactored a bit and came across some minor bugs and possible improvements in the tests.

Improve tests

---

package.json
test/utils/__snapshots__/scaffold.spec.ts.snap

See the doc here: https://docs.npmjs.com/files/package.json#repository

fix repository url

---

src/templates/init/Jenkinsfile

Use pipeline directly from the library

Use pipeline directly from the library

---

package.json
src/commands/generate-odata-client.ts
src/commands/help-page.ts
src/utils/manifest-yaml.ts
test/__snapshots__/add-approuter.spec.ts.snap
test/__snapshots__/add-cds.spec.ts.snap
test/__snapshots__/add-cx-server.spec.ts.snap
test/__snapshots__/init.spec.ts.snap
test/add-approuter.spec.ts
test/add-cds.spec.ts
test/add-cx-server.spec.ts
test/generate-odata-client.e2e.spec.ts
test/generate-odata-client.spec.ts
test/init.spec.ts
test/package.spec.ts
test/utils/scaffold.spec.ts
yarn.lock

The generator logs it progress when typing:
```
generate-odata-client -i input -o output
```
But all logging was lost when typing:
```
sap-cloud-sdk generate-odata-client -i input -o output
```
So I piped the stdout of the generator command to the stdout of the CLI process
Closes #55"

Added logging on generator

---

README.md

I forgot to run `prepack` so the readme still contains the links to the version 0.1.9 which is not the latest one.

Fix: Update readme

---

README.md

Add a reference to docs from a CLI repo's Readme

Add reference to docs

---

README.md
package.json

Release version 0.1.11 afterthe cx-server script download issue was fixed (#104)

patch version 0.1.11

---

.github/workflows/test.yml
.reuse/dep5
CONTRIBUTING.md
LICENSES/Apache-2.0.txt
NOTICE
README.md

chore: Switch from CLA to DCO

---

README.md
src/commands/generate-odata-client.ts
src/templates/add-cds/.npmrc
src/templates/init/.npmrc
src/utils/generator-options.ts
test/init.spec.ts
test/init.vanilla.e2e.spec.ts
test/utils/__snapshots__/templates.spec.ts.snap
test/utils/templates.spec.ts

remove npmrc

---

README.md
package.json

Release a new version for the removal of the `.npmrc`.

release 0.1.12

---

test/utils/scaffold.e2e.spec.ts

chore: Fix linting

---

src/commands/package.ts

chore: Prepare for move

---

src/utils/package-json.ts

Remove reference to old sap npm registry

---

README.md
src/templates/init/.pipeline/config.yml.mu
src/templates/init/Jenkinsfile
src/templates/scaffold-readme/README.md

Update the Pipeline template to project "Piper" General Purpose Pipeline.
See https://github.com/SAP/cloud-s4-sdk-pipeline/blob/master/gpp-guide.md for more background.

Replace Cloud SDK Pipeline with General Purpose Pipeline

---

README.md

Deprecate the CLI in the readme

Deprecate the CLI
